
'use client';

import React, { useState } from 'react';
import { z } from "zod";
import { zodResolver } from "@hookform/resolvers/zod";
import { useForm } from "react-hook-form";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
  DialogFooter,
} from '@/components/ui/dialog';
import {
    Form,
    FormControl,
    FormField,
    FormItem,
    FormLabel,
    FormMessage,
} from "@/components/ui/form"
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { useToast } from '@/hooks/use-toast';
import { initiateDeposit, type DepositDetails, type TransactionStatus } from '@/services/broker-api';
import { Loader2, Landmark, CreditCard, Banknote, ExternalLink, AlertTriangle } from 'lucide-react'; // Added AlertTriangle

// Inline SVGs for Nequi, Daviplata, PayPal (simple placeholders)
const NequiIcon = () => <svg xmlns="http://www.w3.org/2000/svg" className="h-4 w-4 mr-2 text-[#FF00FF]" fill="currentColor" viewBox="0 0 16 16"><path d="M8 0a8 8 0 1 0 0 16A8 8 0 0 0 8 0zM4.5 4.5a.5.5 0 0 1 .5-.5h6a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-6a.5.5 0 0 1-.5-.5v-1zm0 3a.5.5 0 0 1 .5-.5h6a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-6a.5.5 0 0 1-.5-.5v-1zm0 3a.5.5 0 0 1 .5-.5h4a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-4a.5.5 0 0 1-.5-.5v-1z"/></svg>;
const DaviplataIcon = () => <svg xmlns="http://www.w3.org/2000/svg" className="h-4 w-4 mr-2 text-[#E00000]" fill="currentColor" viewBox="0 0 16 16"><path d="M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16zM6 4.5a.5.5 0 0 1 .5-.5h3a.5.5 0 0 1 .5.5V5h1v-.5a1.5 1.5 0 0 0-1.5-1.5h-3A1.5 1.5 0 0 0 5 5V6H4v-.5a.5.5 0 0 1 .5-.5H6V4.5zm5 4.707l-3.5 3.5a.5.5 0 0 1-.707 0l-1.5-1.5a.5.5 0 1 1 .707-.707L7.5 11.293l3.146-3.147a.5.5 0 0 1 .708.708z"/></svg>;
const PayPalIcon = () => <svg xmlns="http://www.w3.org/2000/svg" className="h-4 w-4 mr-2 text-[#0070BA]" fill="currentColor" viewBox="0 0 16 16"><path d="M14.06 3.713c.124 1.07-.091 1.834-.31 2.533-.217.694-.502 1.286-.84 1.766-.34.474-.747.857-1.205 1.123-.46.269-.975.411-1.53.411H7.563c-.549 0-.994-.098-1.33-.294-.334-.196-.58-.48-.73-.844a.87.87 0 0 1-.239-1.187c.126-.32.347-.575.658-.75.31-.174.69-.26 1.12-.26h1.41c.186 0 .35-.04.49-.117a.53.53 0 0 0 .28-.31c.06-.118.09-.26.09-.424 0-.13-.02-.24-.06-.33a.44.44 0 0 0-.18-.216.7.7 0 0 0-.29-.132.88.88 0 0 0-.36-.051H7.47c-1.13 0-1.95-.42-2.46-1.25a2.8 2.8 0 0 1-.04-2.45 3.7 3.7 0 0 1 2.7-1.965C8.43 2.01 9.52 2 10.76 2c.49 0 .93.04 1.3.117.37.076.68.184.93.32.25.137.44.296.57.478.13.18.2.375.2.582 0 .126-.02.24-.06.34a.5.5 0 0 1-.18.227.69.69 0 0 1-.29.137.88.88 0 0 1-.36.05h-.5c-.18 0-.34.04-.49.117a.5.5 0 0 0-.28.31c-.06.117-.09.26-.09.424 0 .31.08.562.25.752.17.19.43.287.79.287h.28c.48 0 .89.16 1.23.478.34.318.54.74.6 1.26z"/></svg>;


interface DepositDialogProps {
  isOpen: boolean;
  onOpenChange: (open: boolean) => void;
}

// Updated schema with new methods
const depositFormSchema = z.object({
  amount: z.coerce.number().positive({ message: "Amount must be positive." }).min(5, { message: "Minimum deposit is $5."}),
  method: z.enum(["bank_transfer", "card", "nequi", "daviplata", "paypal"], {
    required_error: "Please select a deposit method.",
  }),
  currency: z.literal("USD", { // Currently only supporting USD, adjust if needed
    errorMap: () => ({ message: "Only USD deposits are currently supported." }),
  }),
  // Added optional field for Nequi/Daviplata identifier
  customerIdentifier: z.string().optional(),
});

type DepositFormValues = z.infer<typeof depositFormSchema>;

export function DepositDialog({ isOpen, onOpenChange }: DepositDialogProps) {
  const { toast } = useToast();
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [apiError, setApiError] = useState<string | null>(null); // State for API errors

  const form = useForm<DepositFormValues>({
    resolver: zodResolver(depositFormSchema),
    defaultValues: {
      amount: 50, // Default amount
      method: undefined,
      currency: "USD",
      customerIdentifier: "",
    },
  });

  async function onSubmit(values: DepositFormValues) {
    setIsSubmitting(true);
    setApiError(null); // Clear previous errors
    console.log("Deposit form values:", values);

    // IMPORTANT: This function requires a secure backend endpoint.
    // The frontend should NOT handle payment processing directly.
    // The backend needs to integrate with the payment processor (Stripe, PayPal, Nequi API, etc.)
    const depositDetails: DepositDetails = {
      amount: values.amount,
      method: values.method,
      currency: values.currency,
      // Add specific details needed by the backend based on the method
      // For card: A payment token generated by Stripe Elements/Checkout would be passed here.
      // For Nequi/Daviplata: The phone number or identifier.
      // For PayPal: The order ID after PayPal approval on the client-side.
      ...(values.method === 'nequi' || values.method === 'daviplata' ? { customer_identifier: values.customerIdentifier } : {}),
      // payment_token: 'tok_...', // Example: Token from Stripe Elements
    };

    try {
      // This call attempts to reach your backend via broker-api.ts -> initiateDeposit
      // The initiateDeposit function itself needs to make a fetch call to your *actual* backend API endpoint.
      toast({
          title: "Processing Deposit...",
          description: `Sending request for $${values.amount} via ${values.method}.`,
      });
      const result: TransactionStatus = await initiateDeposit(depositDetails);
      console.log("Deposit initiation result from backend:", result);

      // Handle different statuses returned by the backend
      if (result.status === 'completed') {
           toast({
              title: "Deposit Successful!",
              description: `Successfully deposited ${formatCurrency(values.amount)}. Transaction ID: ${result.transactionId}`,
              variant: "default", // Use default for success
           });
           form.reset(); // Reset form on success
           onOpenChange(false); // Close dialog on success
      } else if (result.status === 'pending' || result.status === 'processing') {
           toast({
              title: "Deposit Pending",
              description: `Your deposit is processing. Status: ${result.status}. Transaction ID: ${result.transactionId}. ${result.message || ''}`,
              variant: "default",
           });
            form.reset(); // Reset form even if pending
            onOpenChange(false); // Close dialog
      } else if (result.status === 'requires_action') {
           toast({
               title: "Action Required",
               description: `Further action needed for your deposit. ${result.message || 'Please check instructions.'} Transaction ID: ${result.transactionId}`,
               variant: "default", // Or a specific 'warning' variant if you add one
           });
            // Optionally redirect user or show specific instructions based on result.message
            onOpenChange(false); // Close dialog for now
      } else { // failed, cancelled
            setApiError(`Deposit ${result.status}: ${result.message || 'Please try again or contact support.'} (ID: ${result.transactionId})`);
            toast({
              variant: "destructive",
              title: `Deposit ${result.status.charAt(0).toUpperCase() + result.status.slice(1)}`,
              description: `${result.message || 'An error occurred.'} (ID: ${result.transactionId})`,
            });
      }

    } catch (error: any) {
      console.error("Deposit initiation failed in component:", error);
      const errorMessage = error.message || "Could not initiate deposit. Please ensure backend is available and payment details are correct.";
      setApiError(errorMessage); // Display error within the dialog
      toast({
        variant: "destructive",
        title: "Deposit Request Failed",
        description: errorMessage,
      });
    } finally {
      setIsSubmitting(false);
    }
  }

  // Helper function for currency formatting
   const formatCurrency = (value: number | string | undefined, currency: string = 'USD') => {
     const numValue = Number(value);
     if (isNaN(numValue)) return '$--.--';
     return new Intl.NumberFormat('en-US', { style: 'currency', currency: currency }).format(numValue);
   };


  return (
    <Dialog open={isOpen} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-[425px]">
        <DialogHeader>
          <DialogTitle>Deposit Funds</DialogTitle>
          <DialogDescription>
            Add funds to your HIBLLX account. Requires secure backend integration with payment processors.
          </DialogDescription>
        </DialogHeader>
        <Form {...form}>
            <form onSubmit={form.handleSubmit(onSubmit)} className="grid gap-4 py-4">
                {/* Amount */}
                <FormField
                  control={form.control}
                  name="amount"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>Amount (USD)</FormLabel>
                      <FormControl>
                         <div className="relative">
                           <Banknote className="absolute left-2.5 top-2.5 h-4 w-4 text-muted-foreground" />
                           <Input
                            type="number"
                            placeholder="e.g., 100"
                            min="5"
                            step="any" // Allow decimals
                            className="pl-8" // Add padding for icon
                            disabled={isSubmitting}
                            {...field}
                            />
                         </div>
                      </FormControl>
                      <FormMessage />
                    </FormItem>
                  )}
                />

                {/* Method */}
                <FormField
                  control={form.control}
                  name="method"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>Deposit Method</FormLabel>
                      <Select onValueChange={field.onChange} value={field.value} disabled={isSubmitting}>
                        <FormControl>
                          <SelectTrigger>
                            <SelectValue placeholder="Select a method" />
                          </SelectTrigger>
                        </FormControl>
                        <SelectContent>
                           <SelectItem value="card">
                             <div className="flex items-center">
                                <CreditCard className="mr-2 h-4 w-4 text-muted-foreground" /> Credit/Debit Card (via Backend/Stripe)
                             </div>
                          </SelectItem>
                          <SelectItem value="bank_transfer">
                            <div className="flex items-center">
                                <Landmark className="mr-2 h-4 w-4 text-muted-foreground" /> Bank Transfer (via Backend/Plaid)
                            </div>
                          </SelectItem>
                           <SelectItem value="paypal">
                              <div className="flex items-center">
                                 <PayPalIcon /> PayPal (via Backend)
                              </div>
                           </SelectItem>
                            <SelectItem value="nequi">
                               <div className="flex items-center">
                                 <NequiIcon /> Nequi (Colombia - via Backend)
                               </div>
                           </SelectItem>
                           <SelectItem value="daviplata">
                               <div className="flex items-center">
                                 <DaviplataIcon /> Daviplata (Colombia - via Backend)
                               </div>
                           </SelectItem>
                          {/* <SelectItem value="crypto" disabled>Crypto (Coming Soon)</SelectItem> */}
                        </SelectContent>
                      </Select>
                      <FormMessage />
                    </FormItem>
                  )}
                />

                 {/* Method-Specific UI Elements - Placeholders for required integrations */}
                 {form.watch("method") === "card" && (
                    <div className="p-3 border rounded-md bg-muted/50 space-y-2">
                        <p className="text-sm font-medium">Card Payment (Secure Integration Required)</p>
                        <p className="text-xs text-muted-foreground">
                           Requires integration with a payment gateway like Stripe Elements or Checkout on the frontend,
                           which generates a secure token. This token is then sent to your backend for processing.
                           <strong className='block mt-1'>Do not handle raw card details here.</strong>
                        </p>
                        {/* Placeholder: Real integration would use Stripe Elements component here */}
                        <div className='p-2 border border-dashed rounded text-center text-sm text-muted-foreground'>[Stripe Elements Placeholder]</div>
                    </div>
                 )}
                 {form.watch("method") === "bank_transfer" && (
                    <div className="p-3 border rounded-md bg-muted/50 space-y-2">
                         <p className="text-sm font-medium">Bank Transfer (Integration Required)</p>
                         <Button variant="outline" className="w-full" disabled>
                             <Landmark className="mr-2 h-4 w-4" /> Connect Bank via Plaid (Backend Integration)
                         </Button>
                         <p className="text-xs text-muted-foreground">Requires frontend integration with Plaid Link and backend handling of Plaid tokens to initiate ACH/transfer.</p>
                    </div>
                 )}
                 {form.watch("method") === "paypal" && (
                     <div className="p-3 border rounded-md bg-muted/50 space-y-2">
                          <p className="text-sm font-medium">PayPal Checkout (Integration Required)</p>
                          <Button variant="outline" className="w-full" disabled>
                              <PayPalIcon /> Proceed with PayPal (Frontend/Backend Integration)
                          </Button>
                          <p className="text-xs text-muted-foreground">Requires frontend integration with PayPal SDK to open checkout, and backend to capture the payment using the approved order ID.</p>
                     </div>
                 )}
                 {(form.watch("method") === "nequi" || form.watch("method") === "daviplata") && (
                     <FormField
                       control={form.control}
                       name="customerIdentifier"
                       render={({ field }) => (
                         <FormItem className="p-3 border rounded-md bg-muted/50 space-y-2">
                           <FormLabel className="text-sm font-medium">
                              {form.watch("method") === "nequi" ? "Nequi Phone Number" : "Daviplata Identifier"} (Integration Required)
                           </FormLabel>
                           <FormControl>
                              <Input
                                 placeholder={form.watch("method") === "nequi" ? "e.g., 3001234567" : "e.g., Daviplata Number"}
                                 type="tel"
                                 disabled={isSubmitting}
                                 {...field}
                               />
                           </FormControl>
                            <Button variant="outline" className="w-full" type="button" disabled>
                              {form.watch("method") === "nequi" ? <NequiIcon /> : <DaviplataIcon />}
                              Initiate {form.watch("method") === "nequi" ? "Nequi Push" : "Daviplata Request"} (Backend Integration)
                            </Button>
                           <p className="text-xs text-muted-foreground">Requires backend integration with Nequi/Daviplata APIs for push payments or payment requests.</p>
                           <FormMessage />
                         </FormItem>
                       )}
                     />
                 )}

                 {/* API Error Display */}
                 {apiError && (
                     <div className="p-3 border border-destructive/50 rounded-md bg-destructive/10 text-destructive text-sm flex items-center gap-2">
                         <AlertTriangle className="h-4 w-4" />
                         {apiError}
                     </div>
                 )}


                <DialogFooter>
                  <Button variant="outline" onClick={() => onOpenChange(false)} type="button" disabled={isSubmitting}>
                    Cancel
                  </Button>
                  <Button type="submit" disabled={isSubmitting || !form.formState.isValid}>
                    {isSubmitting && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}
                    {isSubmitting ? 'Processing...' : 'Confirm Deposit'}
                  </Button>
                </DialogFooter>
            </form>
        </Form>
      </DialogContent>
    </Dialog>
  );
}
